//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace BowlersBuddyXam
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<tblBall>();
                db.CreateTable<tblBowler>();
                db.CreateTable<tblFrame>();
                db.CreateTable<tblGame>();
                db.CreateTable<tblLeague>();
                db.CreateTable<tblLeagueBowler>();
                db.CreateTable<tblLocation>();
                db.CreateTable<tblLocationType>();
                db.CreateTable<tblSeries>();
                db.CreateTable<tblSeriesGames>();
                db.CreateTable<tblThrow>();
            }
        }
    }
    public partial class tblBall
    {
        [PrimaryKey]
        public Int64 ball_id { get; set; }
        
    }
    
    public partial class tblBowler
    {
        [PrimaryKey]
        public Int32 bowler_id { get; set; }
        
        [MaxLength(30)]
        public String bowler_name { get; set; }
        
        public Boolean? is_left_handed { get; set; }
        
        public Boolean? is_right_handed { get; set; }
        
        [MaxLength(1)]
        public String gender { get; set; }
        
        [MaxLength(18)]
        public String abc_nbr { get; set; }
        
    }
    
    public partial class tblFrame
    {
        [NotNull]
        public Int32 frame_nbr { get; set; }
        
        [NotNull]
        public Int32 game_id { get; set; }
        
        [NotNull]
        public Int16 frame_number { get; set; }
        
        [NotNull]
        public Boolean is_strike { get; set; }
        
        [NotNull]
        public Boolean is_spare { get; set; }
        
        [NotNull]
        public Boolean is_tenth { get; set; }
        
        [NotNull]
        public Int32 total_pin_count { get; set; }
        
    }
    
    public partial class tblGame
    {
        [PrimaryKey]
        public Int64 game_id { get; set; }
        
        [NotNull]
        public DateTime game_date { get; set; }
        
        [NotNull]
        public Boolean is_practice { get; set; }
        
        [NotNull]
        public Int32 location_id { get; set; }
        
        [NotNull]
        public Int32 final_score { get; set; }
        
        [NotNull]
        public Boolean is_absentee_score { get; set; }
        
        [NotNull]
        public Int32 odd_lane_nbr { get; set; }
        
        [NotNull]
        public Int32 even_lane_nbr { get; set; }
        
        [MaxLength(200)]
        [NotNull]
        public String comment { get; set; }
        
        [NotNull]
        public Int32 bowler_id { get; set; }
        
    }
    
    public partial class tblLeague
    {
        [PrimaryKey]
        public Int64 league_id { get; set; }
        
        [MaxLength(25)]
        [NotNull]
        public String league_name { get; set; }
        
        [MaxLength(30)]
        [NotNull]
        public String league_president { get; set; }
        
        [MaxLength(30)]
        [NotNull]
        public String league_secretary { get; set; }
        
        [NotNull]
        public Int32 location_id { get; set; }
        
    }
    
    public partial class tblLeagueBowler
    {
        [PrimaryKey]
        public Int32 league_bowler_id { get; set; }
        
        [NotNull]
        public Int32 league_id { get; set; }
        
        [NotNull]
        public Int32 bowler_id { get; set; }
        
        [MaxLength(30)]
        [NotNull]
        public String season { get; set; }
        
        [NotNull]
        public DateTime season_start_date { get; set; }
        
        [NotNull]
        public DateTime season_end_date { get; set; }
        
        [MaxLength(10)]
        [NotNull]
        public String bowling_night { get; set; }
        
    }
    
    public partial class tblLocation
    {
        [PrimaryKey]
        public Int64 location_id { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String location_name { get; set; }
        
        [NotNull]
        public Int32 location_type_id { get; set; }
        
    }
    
    public partial class tblLocationType
    {
        [PrimaryKey]
        public Int64 location_type_id { get; set; }
        
        [MaxLength(20)]
        [NotNull]
        public String location_type_name { get; set; }
        
        [MaxLength(100)]
        public String location_type_desc { get; set; }
        
    }
    
    public partial class tblSeries
    {
        [PrimaryKey]
        public Int64 series_id { get; set; }
        
        [NotNull]
        public Int32 game_count { get; set; }
        
        [MaxLength(200)]
        [NotNull]
        public String comment { get; set; }
        
        [NotNull]
        public Boolean is_multiday { get; set; }
        
        [NotNull]
        public DateTime start_date { get; set; }
        
        [NotNull]
        public DateTime end_date { get; set; }
        
        [NotNull]
        public Int32 series_score { get; set; }
        
        [NotNull]
        public Int32 bowler_id { get; set; }
        
    }
    
    public partial class tblSeriesGames
    {
        [PrimaryKey]
        public Int32 series_game_id { get; set; }
        
        [NotNull]
        public Int32 game_id { get; set; }
        
        [NotNull]
        public Int32 series_id { get; set; }
        
    }
    
    public partial class tblThrow
    {
        [PrimaryKey]
        public Int32 throw_id { get; set; }
        
        [NotNull]
        public Int16 throw_nbr { get; set; }
        
        [NotNull]
        public Int32 frame_nbr { get; set; }
        
        [NotNull]
        public Int32 game_id { get; set; }
        
        [NotNull]
        public Byte pin_1 { get; set; }
        
        [NotNull]
        public Byte pin_2 { get; set; }
        
        [NotNull]
        public Byte pin_3 { get; set; }
        
        [NotNull]
        public Byte pin_4 { get; set; }
        
        [NotNull]
        public Byte pin_5 { get; set; }
        
        [NotNull]
        public Byte pin_6 { get; set; }
        
        [NotNull]
        public Byte pin_7 { get; set; }
        
        [NotNull]
        public Byte pin_8 { get; set; }
        
        [NotNull]
        public Byte pin_9 { get; set; }
        
        [NotNull]
        public Byte pin_10 { get; set; }
        
        [NotNull]
        public Int16 pin_count { get; set; }
        
        [NotNull]
        public Int32 ball_id { get; set; }
        
        [NotNull]
        public Int32 foot_mark { get; set; }
        
        [NotNull]
        public Int32 target_mark { get; set; }
        
        [NotNull]
        public Int32 actual_mark { get; set; }
        
        [MaxLength(15)]
        [NotNull]
        public String lane_id { get; set; }
        
        [NotNull]
        public Boolean is_split { get; set; }
        
        [MaxLength(200)]
        [NotNull]
        public String comment { get; set; }
        
        [MaxLength(25)]
        [NotNull]
        public String oil_pattern { get; set; }
        
        [MaxLength(25)]
        [NotNull]
        public String lane_condition { get; set; }
        
    }
    
}
